-- AlterTable
ALTER TABLE "Caregiver" ALTER COLUMN "date_created" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Mentor" ALTER COLUMN "date_created" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Patient" ALTER COLUMN "date_created" SET DEFAULT CURRENT_TIMESTAMP;
